/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package kon

import spock.lang.Specification

class AppTest extends Specification {
    def "test tokens"() {
        setup:
        def kon = new Kon()

        when:
        def result = app.greeting

        then:
        result != null
    }
}
